call "%~dp0libs\admin\.compile.bat"
call "%~dp0libs\branding\.compile.bat"
call "%~dp0libs\comments\.compile.bat"
call "%~dp0libs\contents\.compile.bat"
call "%~dp0libs\english_for_free\.compile.bat"
call "%~dp0libs\forbidden\.compile.bat"
call "%~dp0libs\index\.compile.bat"
call "%~dp0libs\irregular_verbs\.compile.bat"
call "%~dp0libs\irregular_verbs_with_shower\.compile.bat"
call "%~dp0libs\notfound\.compile.bat"
call "%~dp0libs\paper\.compile.bat"
call "%~dp0libs\pictures\.compile.bat"
call "%~dp0libs\portfolio\.compile.bat"
call "%~dp0libs\products\.compile.bat"
call "%~dp0libs\search\.compile.bat"
call "%~dp0libs\serguei-eaststreet\.compile.bat"
call "%~dp0libs\serguei-webslides\.compile.bat"
call "%~dp0libs\sitemap\.compile.bat"

pause
